#!/bin/sh
# Setup giant environment

conda activate giant
export GIANT=$HOME/opt/giant/GIAnt:$HOME/opt/giant/GAInT/SRC:$HOME/opt/giant/GIAnT/solver
export PYTHONPATH=$GIANT:$PYTHONPATH
export PATH=$GIANT:$PATH
